export const nationalities = [
  {value: "Afghan", en: "Afghan", th: "อัฟกานิสถาน"},
  {value: "Albanian", en: "Albanian", th: "แอลเบเนีย"},
  {value: "Algerian", en: "Algerian", th: "แอลจีเรีย"},
  {value: "American", en: "American", th: "อเมริกัน"},
  {value: "Andorran", en: "Andorran", th: "อันดอร์รา"},
  {value: "Angolan", en: "Angolan", th: "แองโกลา"},
  {value: "Argentinean", en: "Argentinean", th: "อาร์เจนตินา"},
  {value: "Armenian", en: "Armenian", th: "อาร์เมเนีย"},
  {value: "Australian", en: "Australian", th: "ออสเตรเลีย"},
  {value: "Austrian", en: "Austrian", th: "ออสเตรีย"},
  {value: "Azerbaijani", en: "Azerbaijani", th: "อาเซอร์ไบจาน"},
  {value: "Bahamian", en: "Bahamian", th: "บาฮามาส"},
  {value: "Bahraini", en: "Bahraini", th: "บาห์เรน"},
  {value: "Bangladeshi", en: "Bangladeshi", th: "บังกลาเทศ"},
  {value: "Barbadian", en: "Barbadian", th: "บาร์เบโดส"},
  {value: "Belarusian", en: "Belarusian", th: "เบลารุส"},
  {value: "Belgian", en: "Belgian", th: "เบลเยียม"},
  {value: "Belizean", en: "Belizean", th: "เบลีซ"},
  {value: "Beninese", en: "Beninese", th: "เบนิน"},
  {value: "Bhutanese", en: "Bhutanese", th: "ภูฏาน"},
  {value: "Bolivian", en: "Bolivian", th: "โบลิเวีย"},
  {value: "Bosnian", en: "Bosnian", th: "บอสเนียและเฮอร์เซโกวีนา"},
  {value: "Brazilian", en: "Brazilian", th: "บราซิล"},
  {value: "British", en: "British", th: "อังกฤษ"},
  {value: "Bruneian", en: "Bruneian", th: "บรูไน"},
  {value: "Bulgarian", en: "Bulgarian", th: "บัลแกเรีย"},
  {value: "Burkinese", en: "Burkinese", th: "บูร์กินาฟาโซ"},
  {value: "Burmese", en: "Burmese", th: "พม่า"},
  {value: "Burundian", en: "Burundian", th: "บุรุนดี"},
  {value: "Cambodian", en: "Cambodian", th: "กัมพูชา"},
  {value: "Cameroonian", en: "Cameroonian", th: "แคเมอรูน"},
  {value: "Canadian", en: "Canadian", th: "แคนาดา"},
  {value: "Cape Verdean", en: "Cape Verdean", th: "เคปเวิร์ด"},
  {value: "Central African", en: "Central African", th: "สาธารณรัฐแอฟริกากลาง"},
  {value: "Chadian", en: "Chadian", th: "ชาด"},
  {value: "Chilean", en: "Chilean", th: "ชิลี"},
  {value: "Chinese", en: "Chinese", th: "จีน"},
  {value: "Colombian", en: "Colombian", th: "โคลอมเบีย"},
  {value: "Comoran", en: "Comoran", th: "คอโมโรส"},
  {value: "Congolese", en: "Congolese", th: "คองโก"},
  {value: "Costa Rican", en: "Costa Rican", th: "คอสตาริกา"},
  {value: "Croatian", en: "Croatian", th: "โครเอเชีย"},
  {value: "Cuban", en: "Cuban", th: "คิวบา"},
  {value: "Cypriot", en: "Cypriot", th: "ไซปรัส"},
  {value: "Czech", en: "Czech", th: "เช็ก"},
  {value: "Danish", en: "Danish", th: "เดนมาร์ก"},
  {value: "Djiboutian", en: "Djiboutian", th: "จิบูตี"},
  {value: "Dominican", en: "Dominican", th: "โดมินิกัน"},
  {value: "Dutch", en: "Dutch", th: "ดัตช์"},
  {value: "East Timorese", en: "East Timorese", th: "ติมอร์ตะวันออก"},
  {value: "Ecuadorean", en: "Ecuadorean", th: "เอกวาดอร์"},
  {value: "Egyptian", en: "Egyptian", th: "อียิปต์"},
  {value: "Emirian", en: "Emirian", th: "สหรัฐอาหรับเอมิเรตส์"},
  {
    value: "Equatorial Guinean",
    en: "Equatorial Guinean",
    th: "อิเควทอเรียลกินี",
  },
  {value: "Eritrean", en: "Eritrean", th: "เอริเทรีย"},
  {value: "Estonian", en: "Estonian", th: "เอสโตเนีย"},
  {value: "Ethiopian", en: "Ethiopian", th: "เอธิโอเปีย"},
  {value: "Fijian", en: "Fijian", th: "ฟิจิ"},
  {value: "Filipino", en: "Filipino", th: "ฟิลิปปินส์"},
  {value: "Finnish", en: "Finnish", th: "ฟินแลนด์"},
  {value: "French", en: "French", th: "ฝรั่งเศส"},
  {value: "Gabonese", en: "Gabonese", th: "กาบอง"},
  {value: "Gambian", en: "Gambian", th: "แกมเบีย"},
  {value: "Georgian", en: "Georgian", th: "จอร์เจีย"},
  {value: "German", en: "German", th: "เยอรมนี"},
  {value: "Ghanaian", en: "Ghanaian", th: "กานา"},
  {value: "Greek", en: "Greek", th: "กรีซ"},
  {value: "Grenadian", en: "Grenadian", th: "เกรเนดา"},
  {value: "Guatemalan", en: "Guatemalan", th: "กัวเตมาลา"},
  {value: "Guinea-Bissauan", en: "Guinea-Bissauan", th: "กินี-บิสเซา"},
  {value: "Guinean", en: "Guinean", th: "กินี"},
  {value: "Guyanese", en: "Guyanese", th: "กายอานา"},
  {value: "Haitian", en: "Haitian", th: "เฮติ"},
  {value: "Herzegovinian", en: "Herzegovinian", th: "เฮอร์เซโกวีนา"},
  {value: "Honduran", en: "Honduran", th: "ฮอนดูรัส"},
  {value: "Hungarian", en: "Hungarian", th: "ฮังการี"},
  {value: "Icelander", en: "Icelander", th: "ไอซ์แลนด์"},
  {value: "Indian", en: "Indian", th: "อินเดีย"},
  {value: "Indonesian", en: "Indonesian", th: "อินโดนีเซีย"},
  {value: "Iranian", en: "Iranian", th: "อิหร่าน"},
  {value: "Iraqi", en: "Iraqi", th: "อิรัก"},
  {value: "Irish", en: "Irish", th: "ไอร์แลนด์"},
  {value: "Israeli", en: "Israeli", th: "อิสราเอล"},
  {value: "Italian", en: "Italian", th: "อิตาลี"},
  {value: "Ivorian", en: "Ivorian", th: "ไอวอรีโคสต์"},
  {value: "Jamaican", en: "Jamaican", th: "จาเมกา"},
  {value: "Japanese", en: "Japanese", th: "ญี่ปุ่น"},
  {value: "Jordanian", en: "Jordanian", th: "จอร์แดน"},
  {value: "Kazakhstani", en: "Kazakhstani", th: "คาซัคสถาน"},
  {value: "Kenyan", en: "Kenyan", th: "เคนยา"},
  {
    value: "Kittian and Nevisian",
    en: "Kittian and Nevisian",
    th: "เซนต์คิตส์และเนวิส",
  },
  {value: "Kuwaiti", en: "Kuwaiti", th: "คูเวต"},
  {value: "Kyrgyz", en: "Kyrgyz", th: "คีร์กีซสถาน"},
  {value: "Laotian", en: "Laotian", th: "ลาว"},
  {value: "Latvian", en: "Latvian", th: "ลัตเวีย"},
  {value: "Lebanese", en: "Lebanese", th: "เลบานอน"},
  {value: "Liberian", en: "Liberian", th: "ไลบีเรีย"},
  {value: "Libyan", en: "Libyan", th: "ลิเบีย"},
  {value: "Liechtensteiner", en: "Liechtensteiner", th: "ลิกเตนสไตน์"},
  {value: "Lithuanian", en: "Lithuanian", th: "ลิทัวเนีย"},
  {value: "Luxembourger", en: "Luxembourger", th: "ลักเซมเบิร์ก"},
  {value: "Macedonian", en: "Macedonian", th: "มาซิโดเนียเหนือ"},
  {value: "Malagasy", en: "Malagasy", th: "มาดากัสการ์"},
  {value: "Malawian", en: "Malawian", th: "มาลาวี"},
  {value: "Malaysian", en: "Malaysian", th: "มาเลเซีย"},
  {value: "Maldivan", en: "Maldivan", th: "มัลดีฟส์"},
  {value: "Malian", en: "Malian", th: "มาลี"},
  {value: "Maltese", en: "Maltese", th: "มอลตา"},
  {value: "Marshallese", en: "Marshallese", th: "หมู่เกาะมาร์แชลล์"},
  {value: "Mauritanian", en: "Mauritanian", th: "มอริเตเนีย"},
  {value: "Mauritian", en: "Mauritian", th: "มอริเชียส"},
  {value: "Mexican", en: "Mexican", th: "เม็กซิโก"},
  {value: "Micronesian", en: "Micronesian", th: "ไมโครนีเซีย"},
  {value: "Moldovan", en: "Moldovan", th: "มอลโดวา"},
  {value: "Monacan", en: "Monacan", th: "โมนาโก"},
  {value: "Mongolian", en: "Mongolian", th: "มองโกเลีย"},
  {value: "Moroccan", en: "Moroccan", th: "โมร็อกโก"},
  {value: "Mosotho", en: "Mosotho", th: "เลโซโท"},
  {value: "Motswana", en: "Motswana", th: "บอตสวานา"},
  {value: "Mozambican", en: "Mozambican", th: "โมซัมบิก"},
  {value: "Namibian", en: "Namibian", th: "นามิเบีย"},
  {value: "Nauruan", en: "Nauruan", th: "นาอูรู"},
  {value: "Nepalese", en: "Nepalese", th: "เนปาล"},
  {value: "New Zealander", en: "New Zealander", th: "นิวซีแลนด์"},
  {value: "Nicaraguan", en: "Nicaraguan", th: "นิการากัว"},
  {value: "Nigerian", en: "Nigerian", th: "ไนจีเรีย"},
  {value: "Nigerien", en: "Nigerien", th: "ไนเจอร์"},
  {value: "North Korean", en: "North Korean", th: "เกาหลีเหนือ"},
  {value: "Northern Irish", en: "Northern Irish", th: "ไอร์แลนด์เหนือ"},
  {value: "Norwegian", en: "Norwegian", th: "นอร์เวย์"},
  {value: "Omani", en: "Omani", th: "โอมาน"},
  {value: "Pakistani", en: "Pakistani", th: "ปากีสถาน"},
  {value: "Palauan", en: "Palauan", th: "ปาเลา"},
  {value: "Palestinian", en: "Palestinian", th: "ปาเลสไตน์"},
  {value: "Panamanian", en: "Panamanian", th: "ปานามา"},
  {value: "Papua New Guinean", en: "Papua New Guinean", th: "ปาปัวนิวกินี"},
  {value: "Paraguayan", en: "Paraguayan", th: "ปารากวัย"},
  {value: "Peruvian", en: "Peruvian", th: "เปรู"},
  {value: "Polish", en: "Polish", th: "โปแลนด์"},
  {value: "Portuguese", en: "Portuguese", th: "โปรตุเกส"},
  {value: "Qatari", en: "Qatari", th: "กาตาร์"},
  {value: "Romanian", en: "Romanian", th: "โรมาเนีย"},
  {value: "Russian", en: "Russian", th: "รัสเซีย"},
  {value: "Rwandan", en: "Rwandan", th: "รวันดา"},
  {value: "Saint Lucian", en: "Saint Lucian", th: "เซนต์ลูเซีย"},
  {value: "Salvadoran", en: "Salvadoran", th: "เอลซัลวาดอร์"},
  {value: "Samoan", en: "Samoan", th: "ซามัว"},
  {value: "San Marinese", en: "San Marinese", th: "ซานมารีโน"},
  {value: "Sao Tomean", en: "Sao Tomean", th: "เซาตูเมและปรินซิปี"},
  {value: "Saudi", en: "Saudi", th: "ซาอุดีอาระเบีย"},
  {value: "Scottish", en: "Scottish", th: "สกอตแลนด์"},
  {value: "Senegalese", en: "Senegalese", th: "เซเนกัล"},
  {value: "Serbian", en: "Serbian", th: "เซอร์เบีย"},
  {value: "Seychellois", en: "Seychellois", th: "เซเชลส์"},
  {value: "Sierra Leonean", en: "Sierra Leonean", th: "เซียร์ราลีโอน"},
  {value: "Singaporean", en: "Singaporean", th: "สิงคโปร์"},
  {value: "Slovakian", en: "Slovakian", th: "สโลวาเกีย"},
  {value: "Slovenian", en: "Slovenian", th: "สโลวีเนีย"},
  {value: "Solomon Islander", en: "Solomon Islander", th: "หมู่เกาะโซโลมอน"},
  {value: "Somali", en: "Somali", th: "โซมาเลีย"},
  {value: "South African", en: "South African", th: "แอฟริกาใต้"},
  {value: "South Korean", en: "South Korean", th: "เกาหลีใต้"},
  {value: "Spanish", en: "Spanish", th: "สเปน"},
  {value: "Sri Lankan", en: "Sri Lankan", th: "ศรีลังกา"},
  {value: "Sudanese", en: "Sudanese", th: "ซูดาน"},
  {value: "Surinamer", en: "Surinamer", th: "ซูรินาเม"},
  {value: "Swazi", en: "Swazi", th: "สวาซิแลนด์"},
  {value: "Swedish", en: "Swedish", th: "สวีเดน"},
  {value: "Swiss", en: "Swiss", th: "สวิตเซอร์แลนด์"},
  {value: "Syrian", en: "Syrian", th: "ซีเรีย"},
  {value: "Taiwanese", en: "Taiwanese", th: "ไต้หวัน"},
  {value: "Tajik", en: "Tajik", th: "ทาจิกิสถาน"},
  {value: "Tanzanian", en: "Tanzanian", th: "แทนซาเนีย"},
  {value: "Thai", en: "Thai", th: "ไทย"},
  {value: "Togolese", en: "Togolese", th: "โตโก"},
  {value: "Tongan", en: "Tongan", th: "ตองกา"},
  {
    value: "Trinidadian/Tobagonian",
    en: "Trinidadian/Tobagonian",
    th: "ตรินิแดดและโตเบโก",
  },
  {value: "Tunisian", en: "Tunisian", th: "ตูนิเซีย"},
  {value: "Turkish", en: "Turkish", th: "ตุรกี"},
  {value: "Tuvaluan", en: "Tuvaluan", th: "ตูวาลู"},
  {value: "Ugandan", en: "Ugandan", th: "ยูกันดา"},
  {value: "Ukrainian", en: "Ukrainian", th: "ยูเครน"},
  {value: "Uruguayan", en: "Uruguayan", th: "อุรุกวัย"},
  {value: "Uzbekistani", en: "Uzbekistani", th: "อุซเบกิสถาน"},
  {value: "Venezuelan", en: "Venezuelan", th: "เวเนซุเอลา"},
  {value: "Vietnamese", en: "Vietnamese", th: "เวียดนาม"},
  {value: "Welsh", en: "Welsh", th: "เวลส์"},
  {value: "Yemenite", en: "Yemenite", th: "เยเมน"},
  {value: "Zambian", en: "Zambian", th: "แซมเบีย"},
  {value: "Zimbabwean", en: "Zimbabwean", th: "ซิมบับเว"},
];
